const serverRoot = process.env.NODE_ENV === 'production' ? '' : 'http://localhost:3000';

const LOGIN_STATE = 'LOGIN';
const LOGOUT_STATE = 'LOGOUT';
const PENDING_STATE = 'AUTH_PENDING';
const GET_USER_DATA = 'GET_USER_DATA';

const POST_ACTION_PENDING = 'POST_ACTION_PENDING';
const POST_ACTION_DONE = 'POST_ACTION_DONE';
const GET_MY_POSTS_DONE = 'GET_MY_POSTS_DONE';
const GET_ALL_POSTS_DONE = 'GET_ALL_POSTS_DONE';

export {
  serverRoot,
  LOGIN_STATE, LOGOUT_STATE, PENDING_STATE, GET_USER_DATA,
  POST_ACTION_PENDING, POST_ACTION_DONE, GET_MY_POSTS_DONE, GET_ALL_POSTS_DONE,
};
